//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezvax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentariu
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int idPost { get; set; }
        public string text { get; set; }
        public System.DateTime data { get; set; }
        public int likeCounter { get; set; }
    
        public virtual Postare Postare { get; set; }
        public virtual Users Users { get; set; }
    }
}
