//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezvax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProfilMedical
    {
        public int id { get; set; }
        public int idUser { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Range(18, 99)]
        [DisplayName("Varsta")]
        public int varsta { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Gen")]
        public string gen { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Grupa sanguina")]
        public string grupaSanguina { get; set; }
        [DisplayName("Boli cronice")]
        public string boliCronice { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Anticorpi")]
        public string anticorpi { get; set; }
        [DisplayName("Simptome")]
        public string simptome { get; set; }
        [NotMapped]
        public List<Simptome> simptomes { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "This field is required")]
        public List<Gen> genders { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "This field is required")]
        public List<Anticorpi> Anticorpis { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "This field is required")]
        public List<GrupeSange> grupeSange { get; set; }
        public string ageErrorMessage { get; set; }
        public virtual Users Users { get; set; }
    }
}
