//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezvax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProfilMedical
    {
        public int id { get; set; }
        public int idUser { get; set; }
        [Range(18,120)]
        public int varsta { get; set; }
        public string gen { get; set; }
        public string grupaSanguina { get; set; }
        public string boliCronice { get; set; }
        public string anticorpi { get; set; }
        public Nullable<int> idSimptom { get; set; }
        public List<Simptome> simptome { get; set; }
        [NotMapped]
        public virtual Simptome Simptome { get; set; }
        public virtual Users Users { get; set; }
    }
}
