//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZVax_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postare()
        {
            this.Comentariu = new HashSet<Comentariu>();
        }
    
        public int id { get; set; }
        public int idUser { get; set; }
        public string titlu { get; set; }
        public string text { get; set; }
        public System.DateTime data { get; set; }
        public int likeCounter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentariu> Comentariu { get; set; }
        public virtual Users Users { get; set; }
    }
}
