//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZVax_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilMedical
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int varsta { get; set; }
        public string gen { get; set; }
        public string grupaSanguina { get; set; }
        public string boliCronice { get; set; }
        public string anticorpi { get; set; }
        public string simptome { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
