//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZVax_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoc
    {
        public int id { get; set; }
        public int idClinica { get; set; }
        public Nullable<int> stocAstraZeneca { get; set; }
        public Nullable<int> stocPfizer { get; set; }
        public Nullable<int> stocSputnik { get; set; }
        public Nullable<int> stocModerna { get; set; }
    
        public virtual Clinica Clinica { get; set; }
    }
}
