//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZVax_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccin
    {
        public int id { get; set; }
        public string nume { get; set; }
        public int durataRapel { get; set; }
        public int cantitate { get; set; }
        public string contraindicatii { get; set; }
        public string alergii { get; set; }
    }
}
