//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZVax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int id { get; set; }
        [Required(ErrorMessage ="This field is required")]
        public string nume { get; set; }
        public string prenume { get; set; }
        public string CNP { get; set; }
        public string email { get; set; }
        public string numarTelefon { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string LoginErrorMessage { get; set; }
        [DisplayName("ConfirmPassword")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string ConfirmPassword { get; set; }
    }
}
